# Generated by Django 4.0.2 on 2023-04-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
