# Generated by Django 4.0.2 on 2023-04-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas_resposta', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='comentario_curtidas', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='usuario.post'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(related_name='post_curtidas', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='usuario.comentario'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
